<?php
declare(strict_types=1);
namespace alvin0319\RankText\command;

use alvin0319\RankText\RankTextPlugin;
use pocketmine\command\CommandSender;
use pocketmine\command\PluginCommand;
use pocketmine\level\Position;
use pocketmine\Player;
use pocketmine\plugin\Plugin;
use pocketmine\utils\TextFormat;

class RankTextCommand extends PluginCommand{

	public function __construct(){
		parent::__construct("ranktext", RankTextPlugin::getInstance());
		$this->setPermission("ranktext.command.use");
	}

	public function execute(CommandSender $sender, string $commandLabel, array $args) : bool{
		if($sender instanceof Player){
			$this->getPlugin()->spawnText(Position::fromObject($sender->add(0, 1), $sender->getLevel()));
			$sender->sendMessage(TextFormat::GOLD . "Spawned RankText!");
		}
		return true;
	}

	public function getPlugin(): Plugin{
		return parent::getPlugin(); // TODO: Change the autogenerated stub
	}
}